#!/usr/bin/env python3
# GenieX agent app - generated by the Edge Impulse "GenieX agent app" deployment block.
#
#   camera -> Edge Impulse impulse (.eim, NPU) -> trigger policy
#          -> GenieX (local LLM/VLM, OpenAI-compatible server) -> actions
#
# Everything tunable lives in config.yaml: models, prompts, trigger rules, actions.
# Run `python3 agent.py --mock --image photo.jpg` on any machine to exercise the
# LLM path without a camera or .eim (point geniex.base_url at any OpenAI-compatible
# server for development).

import argparse
import base64
import json
import os
import sys
import time
import urllib.request
from datetime import datetime, timezone

import yaml
from openai import OpenAI


def now_iso():
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


class TriggerPolicy:
    """Fire when a watched class stays above the confidence bar for N consecutive
    inferences, with a cooldown between firings so the LLM is not spammed."""

    def __init__(self, cfg):
        self.watch = set(cfg.get("classes") or [])  # empty = watch every class
        self.ignore = set(cfg.get("ignore_classes") or [])
        self.min_confidence = float(cfg.get("min_confidence", 0.6))
        self.consecutive = int(cfg.get("consecutive_inferences", 2))
        self.cooldown_s = float(cfg.get("cooldown_seconds", 10))
        self.streaks = {}
        self.last_fired = None

    def update(self, candidates):
        """candidates: list of (label, confidence) seen in this inference.
        Returns (label, confidence) when the policy fires, else None."""
        seen = {}
        for label, conf in candidates:
            if label in self.ignore:
                continue
            if self.watch and label not in self.watch:
                continue
            if conf < self.min_confidence:
                continue
            seen[label] = max(conf, seen.get(label, 0.0))

        # streaks reset for labels that dropped out this inference
        for label in list(self.streaks):
            if label not in seen:
                del self.streaks[label]

        in_cooldown = (
            self.last_fired is not None
            and time.monotonic() - self.last_fired < self.cooldown_s
        )
        fired = None
        for label, conf in seen.items():
            self.streaks[label] = self.streaks.get(label, 0) + 1
            if fired is None and self.streaks[label] >= self.consecutive:
                fired = (label, conf)

        if fired and not in_cooldown:
            self.last_fired = time.monotonic()
            self.streaks.clear()
            return fired
        return None


class GenieXAgent:
    def __init__(self, cfg):
        g = cfg["geniex"]
        self.client = OpenAI(
            base_url=g.get("base_url", "http://127.0.0.1:18181/v1"),
            api_key=g.get("api_key", "not-needed"),
        )
        self.model = g["model"]
        self.max_tokens = int(g.get("max_tokens", 512))
        self.temperature = float(g.get("temperature", 0.4))
        a = cfg["agent"]
        self.system_prompt = a["system_prompt"]
        self.task_prompt = a["task_prompt"]
        self.send_image = bool(a.get("send_image", True))

    def run(self, label, confidence, detections, jpeg_bytes=None):
        user_text = self.task_prompt.format(
            label=label,
            confidence=f"{confidence:.2f}",
            detections=json.dumps(detections),
        )
        content = [{"type": "text", "text": user_text}]
        if jpeg_bytes is not None and self.send_image:
            b64 = base64.b64encode(jpeg_bytes).decode("ascii")
            content.append(
                {
                    "type": "image_url",
                    "image_url": {"url": f"data:image/jpeg;base64,{b64}"},
                }
            )
        resp = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": self.system_prompt},
                {"role": "user", "content": content},
            ],
            max_tokens=self.max_tokens,
            temperature=self.temperature,
        )
        return resp.choices[0].message.content


class Actions:
    def __init__(self, cfg):
        self.jsonl_log = cfg.get("jsonl_log")
        self.webhook_url = cfg.get("webhook_url")

    def emit(self, event):
        print(f"\n=== [{event['time']}] {event['label']} ({event['confidence']:.2f}) ===")
        print(event["response"])
        sys.stdout.flush()
        if self.jsonl_log:
            with open(self.jsonl_log, "a") as f:
                f.write(json.dumps(event) + "\n")
        if self.webhook_url:
            try:
                req = urllib.request.Request(
                    self.webhook_url,
                    data=json.dumps(event).encode(),
                    headers={"Content-Type": "application/json"},
                )
                urllib.request.urlopen(req, timeout=10)
            except Exception as e:
                print(f"warning: webhook failed: {e}", file=sys.stderr)


def extract_candidates(res):
    """Map an Edge Impulse runner result to ([(label, confidence)], detections)."""
    r = res.get("result", {})
    if "bounding_boxes" in r:
        detections = [
            {
                "label": b["label"],
                "confidence": round(b["value"], 3),
                "box": [b["x"], b["y"], b["width"], b["height"]],
            }
            for b in r["bounding_boxes"]
        ]
        candidates = [(d["label"], d["confidence"]) for d in detections]
    elif "classification" in r:
        detections = {k: round(v, 3) for k, v in r["classification"].items()}
        candidates = list(r["classification"].items())
    else:
        detections, candidates = {}, []
    return candidates, detections


def run_live(cfg):
    # imported lazily: these need the device-side Edge Impulse Linux SDK
    import cv2
    from edge_impulse_linux.image import ImageImpulseRunner

    model_path = os.path.abspath(cfg["impulse"].get("eim_path", "model.eim"))
    camera_id = int(cfg["impulse"].get("camera_device_id", 0))
    trigger = TriggerPolicy(cfg["trigger"])
    agent = GenieXAgent(cfg)
    actions = Actions(cfg["actions"])

    with ImageImpulseRunner(model_path) as runner:
        info = runner.init()
        params = info["model_parameters"]
        print(
            f"Loaded impulse '{info['project']['name']}' "
            f"(labels: {params['labels']}), watching camera {camera_id}..."
        )
        for res, frame in runner.classifier(camera_id):
            candidates, detections = extract_candidates(res)
            fired = trigger.update(candidates)
            if not fired:
                continue
            label, confidence = fired
            jpeg = None
            ok, buf = cv2.imencode(".jpg", frame)
            if ok:
                jpeg = buf.tobytes()
            print(f"trigger: {label} ({confidence:.2f}) -> asking {agent.model} ...")
            response = agent.run(label, confidence, detections, jpeg)
            actions.emit(
                {
                    "time": now_iso(),
                    "label": label,
                    "confidence": confidence,
                    "detections": detections,
                    "response": response,
                }
            )


def run_mock(cfg, image_path=None):
    """Exercise the trigger -> GenieX -> actions path with a fabricated detection."""
    agent = GenieXAgent(cfg)
    actions = Actions(cfg["actions"])
    label = (cfg["trigger"].get("classes") or ["mock_event"])[0]
    detections = [{"label": label, "confidence": 0.87, "box": [24, 32, 96, 96]}]
    jpeg = None
    if image_path:
        with open(image_path, "rb") as f:
            jpeg = f.read()
    print(f"mock trigger: {label} (0.87) -> asking {agent.model} ...")
    response = agent.run(label, 0.87, detections, jpeg)
    actions.emit(
        {
            "time": now_iso(),
            "label": label,
            "confidence": 0.87,
            "detections": detections,
            "response": response,
        }
    )


def main():
    parser = argparse.ArgumentParser(description="GenieX agent app")
    parser.add_argument("--config", default="config.yaml")
    parser.add_argument(
        "--mock",
        action="store_true",
        help="fire one fabricated trigger instead of running the camera loop",
    )
    parser.add_argument("--image", help="JPEG to attach to the mock trigger")
    args = parser.parse_args()

    with open(args.config) as f:
        cfg = yaml.safe_load(f)

    if args.mock:
        run_mock(cfg, args.image)
    else:
        run_live(cfg)


if __name__ == "__main__":
    main()
