#!/usr/bin/env python3
# Edge Impulse custom deployment block: "GenieX agent app (Linux)"
#
# Reads deployment-metadata.json, renders the agent scaffold (config.yaml +
# README.md templated with this project's classes and prompts), and writes
# deploy.zip to the output folder. Stdlib only - no pip installs in the container.

import argparse
import json
import os
import shutil
import sys

SCAFFOLD_DIR = os.path.join(os.path.dirname(os.path.realpath(__file__)), "scaffold")

DEFAULT_GENIEX_MODEL = "google/gemma-4-E4B-it-qat-q4_0-gguf"

# class names that should not wake the LLM by default
BACKGROUND_NAMES = {"background", "noise", "unknown", "uncertain", "idle", "other", "negative"}


def yaml_str(s):
    return json.dumps(s)  # JSON string quoting is valid YAML


def render_config(project_name, classes, sensor):
    class_list = ", ".join(classes) if classes else "the trained classes"
    system_prompt = (
        f"You are an on-device assistant embedded in '{project_name}'. "
        f"A small Edge Impulse model watches the {sensor} feed and detects: {class_list}. "
        "When it triggers you receive the detection details, and usually the camera frame. "
        "Reply with a short, factual assessment: what is happening, whether it needs "
        "attention, and a one-line recommended action. You run fully on the device; "
        "do not suggest cloud services."
    )
    task_prompt = (
        "The impulse triggered on '{label}' at confidence {confidence}. "
        "All detections this frame: {detections}. Assess the situation."
    )
    ignored = [c for c in classes if c.lower().strip("_ ") in BACKGROUND_NAMES]
    watched = [c for c in classes if c not in ignored]
    if watched:
        classes_block = "  classes:\n" + "\n".join(f"    - {yaml_str(c)}" for c in watched)
    else:
        classes_block = "  classes: []"
    if ignored:
        ignore_block = "  ignore_classes:\n" + "\n".join(f"    - {yaml_str(c)}" for c in ignored)
    else:
        ignore_block = "  ignore_classes: []"

    return f"""# GenieX agent app configuration - edit freely, then re-run: bash run.sh
# Generated for Edge Impulse project: {project_name}

geniex:
  # Any model GenieX can pull: a GGUF from Hugging Face (llama.cpp runtime) or a
  # pre-compiled Qualcomm AI Hub bundle (qairt runtime). The default is a
  # multimodal Gemma 4 that runs on the Hexagon NPU via llama.cpp.
  model: {yaml_str(DEFAULT_GENIEX_MODEL)}
  base_url: "http://127.0.0.1:18181/v1"   # geniex serve; any OpenAI-compatible URL works for dev
  max_tokens: 512
  temperature: 0.4

impulse:
  eim_path: "model.eim"        # downloaded by setup.sh via edge-impulse-linux-runner
  camera_device_id: 0

trigger:
  # Which classes wake the LLM. Empty list = any class.
{classes_block}
{ignore_block}
  min_confidence: 0.6
  consecutive_inferences: 2    # must persist this many inferences in a row
  cooldown_seconds: 10         # minimum seconds between LLM calls

agent:
  send_image: true             # attach the camera frame (needs a vision-capable model)
  system_prompt: {yaml_str(system_prompt)}
  # Available placeholders: {{label}}, {{confidence}}, {{detections}}
  task_prompt: {yaml_str(task_prompt)}

actions:
  jsonl_log: "events.jsonl"    # every event + response, one JSON object per line
  webhook_url: null            # set to POST each event as JSON to your endpoint
"""


def render_readme(project_name, owner, classes, sensor, studio_host, project_id):
    class_list = ", ".join(f"`{c}`" for c in classes) if classes else "(see Studio)"
    sensor_note = ""
    if sensor and sensor != "camera":
        sensor_note = (
            f"\n> **Note**: this impulse uses the `{sensor}` sensor. The generated app is "
            "camera-first; adapt `run_live()` in `agent.py` to the matching "
            "`edge_impulse_linux` runner (e.g. `AudioImpulseRunner`) for other sensors. "
            "`--mock` mode works regardless.\n"
        )
    return f"""# {project_name} - GenieX agent app

Generated by the **GenieX agent app** deployment block for
[{project_name}](https://{studio_host}/studio/{project_id}) (owner: {owner}).

Your impulse (classes: {class_list}) runs continuously on the NPU via the Edge
Impulse Linux runner. When a watched class persists above the confidence
threshold, the app sends the detection - and the camera frame - to a local LLM/VLM
served by [GenieX](https://github.com/qualcomm/GenieX), and the model's assessment
is printed, logged to `events.jsonl`, and optionally POSTed to a webhook.
Everything runs on the device; nothing leaves it.
{sensor_note}
## Supported hardware

Any Snapdragon Linux ARM64 board that both products support - validated on the
**Qualcomm Dragonwing IQ-9075 EVK** and **IQ-8275 EVK**. (GenieX does not run on
x86 or non-Snapdragon ARM.)

## Quickstart (on the device)

```bash
unzip deploy.zip -d geniex-agent && cd geniex-agent
bash setup.sh     # installs GenieX + deps, downloads model.eim, pulls the LLM
bash run.sh       # starts geniex serve if needed, then the agent loop
```

`setup.sh` will ask you to log in to Edge Impulse once, to build and download
`model.eim` for this device (NPU-accelerated where supported).

## Tuning

Everything lives in `config.yaml`:

- `geniex.model` - default `{DEFAULT_GENIEX_MODEL}` (multimodal, llama.cpp/NPU).
  For peak NPU performance try a pre-compiled Qualcomm AI Hub bundle, e.g.
  `ai-hub-models/Qwen2.5-VL-7B-Instruct` (vision) or a smaller text-only model
  with `agent.send_image: false`.
- `trigger.*` - which classes wake the LLM, confidence bar, debounce, cooldown.
- `agent.system_prompt` / `agent.task_prompt` - what the LLM is asked to do.
- `actions.webhook_url` - POST every event as JSON to your own endpoint.

## Developing off-device

`python3 agent.py --mock --image some.jpg` fires one fabricated trigger through
the full LLM path - point `geniex.base_url` at any OpenAI-compatible server
(Ollama, LM Studio, ...) to iterate on prompts from any machine.

## Troubleshooting

- `geniex serve` logs are in `geniex-serve.log`; the server listens on
  `127.0.0.1:18181`. `geniex config get chipset` shows what GenieX detected.
- If VLM image calls fail mentioning ffprobe, install ffmpeg: `sudo apt-get install ffmpeg`.
- Re-download the impulse after retraining: delete `model.eim` and re-run `setup.sh`
  (or `edge-impulse-linux-runner --download model.eim`).
"""


def main():
    parser = argparse.ArgumentParser(description="GenieX agent app deployment block")
    parser.add_argument("--metadata", type=str, required=True)
    args = parser.parse_args()

    with open(args.metadata) as f:
        metadata = json.load(f)

    out_dir = metadata["folders"]["output"]
    project = metadata.get("project", {})
    project_name = project.get("name", "Edge Impulse project")
    owner = project.get("owner", "unknown")
    project_id = project.get("id", "")
    studio_host = project.get("studioHost", "studio.edgeimpulse.com")
    classes = metadata.get("classes", []) or []
    sensor = metadata.get("sensor", "camera") or "camera"

    print(f"Generating GenieX agent app for '{project_name}'")
    print(f"  sensor: {sensor}, classes: {classes}")

    build_dir = "/tmp/geniex-agent-build"
    if os.path.exists(build_dir):
        shutil.rmtree(build_dir)
    shutil.copytree(SCAFFOLD_DIR, build_dir)

    with open(os.path.join(build_dir, "config.yaml"), "w") as f:
        f.write(render_config(project_name, classes, sensor))
    with open(os.path.join(build_dir, "README.md"), "w") as f:
        f.write(render_readme(project_name, owner, classes, sensor, studio_host, project_id))
    # keep the raw metadata around for reference/debugging
    shutil.copy(args.metadata, os.path.join(build_dir, "deployment-metadata.json"))

    os.makedirs(out_dir, exist_ok=True)
    shutil.make_archive(os.path.join(out_dir, "deploy"), "zip", build_dir)
    print(f"Wrote {os.path.join(out_dir, 'deploy.zip')}")


if __name__ == "__main__":
    main()
